includedir=$(prefix)/include

build:

install: $(includedir)/ecclesandking1969.H

$(includedir)/ecclesandking1969.H: ecclesandking1969.H
	cp ecclesandking1969.H $(includedir)

uninstall:
	- rm -f $(includedir)/ecclesandking1969.H

clean:
